package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/emkaytec/forge/internal/ui"
	"github.com/spf13/cobra"
)

type manifestTemplate struct {
	resource string
	filename string
	render   func(name string) string
}

func newGenerateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate starter Forge manifests",
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}

	cmd.AddCommand(
		newGenerateTemplateCommand(manifestTemplate{
			resource: "github-repo",
			filename: "github-repo",
			render:   renderGitHubRepoTemplate,
		}),
		newGenerateTemplateCommand(manifestTemplate{
			resource: "hcp-tf-workspace",
			filename: "hcp-tf-workspace",
			render:   renderHCPTFWorkspaceTemplate,
		}),
		newGenerateTemplateCommand(manifestTemplate{
			resource: "aws-iam-provisioner",
			filename: "aws-iam-provisioner",
			render:   renderAWSIAMProvisionerTemplate,
		}),
		newGenerateTemplateCommand(manifestTemplate{
			resource: "launch-agent",
			filename: "launch-agent",
			render:   renderLaunchAgentTemplate,
		}),
	)

	return cmd
}

func newGenerateTemplateCommand(template manifestTemplate) *cobra.Command {
	var outputDir string

	cmd := &cobra.Command{
		Use:   template.resource + " [name]",
		Short: fmt.Sprintf("Write a starter %s manifest", template.resource),
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			name := strings.TrimSpace(args[0])
			if name == "" {
				return fmt.Errorf("manifest name must not be empty")
			}

			path, err := resolveOutputPath(name, outputDir)
			if err != nil {
				return err
			}

			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return err
			}

			if err := os.WriteFile(path, []byte(template.render(name)), 0o644); err != nil {
				return err
			}

			ui.Success(cmd.OutOrStdout(), fmt.Sprintf("Wrote %s manifest to %s", template.filename, path))
			return nil
		},
	}

	cmd.Flags().StringVar(&outputDir, "dir", "", "Write the generated manifest into this relative directory")

	return cmd
}

func resolveOutputPath(name, dir string) (string, error) {
	if filepath.IsAbs(dir) {
		return "", fmt.Errorf("output directory must be relative, got %q", dir)
	}

	baseDir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	if dir != "" {
		baseDir = filepath.Join(baseDir, dir)
	}

	return filepath.Join(baseDir, name+".yaml"), nil
}

func renderGitHubRepoTemplate(name string) string {
	return fmt.Sprintf(`# Generated by "forge manifest generate github-repo %s".
apiVersion: forge/v1
kind: github-repo
metadata:
  # metadata.name is the stable manifest identifier Forge reports on.
  name: %q
spec:
  # spec.name is the GitHub repository name to create or manage.
  name: %q
  # visibility must be either public or private.
  visibility: public
  # description is optional and should stay sanitized in this public repo.
  description: "Repository created by Forge"
  # topics is optional and should use GitHub topic slugs.
  topics:
    - "platform"
    - "automation"
  # default_branch is optional; Forge defaults it to main when omitted.
  default_branch: main
  # branch_protection enables the baseline protected-branch workflow.
  branch_protection: true
`, name, name, name)
}

func renderHCPTFWorkspaceTemplate(name string) string {
	return fmt.Sprintf(`# Generated by "forge manifest generate hcp-tf-workspace %s".
apiVersion: forge/v1
kind: hcp-tf-workspace
metadata:
  # metadata.name is the stable manifest identifier Forge reports on.
  name: %q
spec:
  # spec.name is the HCP Terraform workspace name.
  name: %q
  # organization is the HCP Terraform organization slug.
  organization: "example-org"
  # project is optional and can group related workspaces.
  project: "platform"
  # vcs_repo is optional and should use the connected VCS identifier.
  vcs_repo: "emkaytec/forge"
  # execution_mode must be remote, local, or agent.
  execution_mode: remote
  # terraform_version is optional and pins the workspace runtime.
  terraform_version: "1.9.8"
`, name, name, name)
}

func renderAWSIAMProvisionerTemplate(name string) string {
	return fmt.Sprintf(`# Generated by "forge manifest generate aws-iam-provisioner %s".
apiVersion: forge/v1
kind: aws-iam-provisioner
metadata:
  # metadata.name is the stable manifest identifier Forge reports on.
  name: %q
spec:
  # spec.name is the AWS IAM role name Forge will manage.
  name: %q
  # account_id is the 12-digit AWS account identifier.
  account_id: "123456789012"
  # oidc_provider is the trusted OIDC issuer host or ARN fragment.
  oidc_provider: "token.actions.githubusercontent.com"
  # oidc_subject is the subject pattern allowed to assume this role.
  oidc_subject: "repo:emkaytec/forge:ref:refs/heads/main"
  # managed_policies is optional and attaches AWS managed policy ARNs.
  managed_policies:
    - "arn:aws:iam::aws:policy/ReadOnlyAccess"
`, name, name, name)
}

func renderLaunchAgentTemplate(name string) string {
	return fmt.Sprintf(`# Generated by "forge manifest generate launch-agent %s".
apiVersion: forge/v1
kind: launch-agent
metadata:
  # metadata.name is the stable manifest identifier Forge reports on.
  name: %q
spec:
  # spec.name is the operator-facing name for this launch agent.
  name: %q
  # label is the macOS launchd label and should stay globally unique.
  label: "dev.emkaytec.%s"
  # command is the full command line launchd should execute.
  command: "/opt/homebrew/bin/brew update"
  schedule:
    # type must be interval or calendar.
    type: interval
    # interval_seconds is required for interval schedules.
    interval_seconds: 86400
    # hour and minute are only used for calendar schedules.
    # hour: 9
    # minute: 30
  # run_at_load controls whether the agent also runs on load.
  run_at_load: true
`, name, name, name, name)
}
